### PR TITLE
Dataset environment handling and simulation run result upload/download

### PR DESCRIPTION
**Pull request by brandomr**
## What's New
This PR adds capabilities for both datasets, simulations, and the overall environment. 

### Datasets
The model for `datasets` now includes `file_names`. This is a simple array of the names of the files (e.g. `[data1.csv, data2.csv]`. The idea is that the HMI will know about the files associated with the `dataset` at the time they create the dataset and will ensure that the files have the same column structure but have unique file names. This is an edge case--in the majority of situations there will be 1:1 mapping of datasets to files. 

Some cases, such as [JHU COVID data](https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data/csse_covid_19_daily_reports) might include multiple files per dataset, but I'm reticent to invest more effort into handling this edge case at the moment.

Currently, the expected flow is:
1. HMI `POSTs` the dataset metadata to TDS
2. HMI `GETs` the filename and dataset `id` to create the pre-signed URL for uploading the file
3. HMI `PUTs` the file to S3 (or minio) using the pre-signed URL
4. When needing to fetch the data, the HMI will use the metadata to find the right `file_name` then do a `GET` to generate a pre-signed download URL

### Simulations
Simulations now have the same mechanism for interacting with S3 (minio) for generating pre-signed URLs. This is a direct copy of the pattern from datasets and will enable simulation runs to have multiple result files. This makes sense if the simulation service is producing multiple files, such as a `csv` and perhaps some `netcdf` file. In the case that the simulation service produces a new model configuration, this has to be sent back as such to TDS via the HMI Server.

### Environment Setup
Key changes include:

1. Moving various things from `settings.py` to the example `env` file. 
2. Removing `data/datasets` since they are not used
3. Read in the `S3_BUCKET` environment variable in the `Makefile` and create the bucket on `make up`
4. Ignore the default bucket in `.gitignore`

> Note: `#3` above will be weird when this is deployed to production, but it seemed reasonable to have a setup whereby the bucket name for development can be arbitrary. We could certainly ditch this though if it presents future/foreseeable issues.

### CODE REVIEW

**Review by toddroper — APPROVED** [review]
Looks good to me.  The only question I have is around the `file_names` list in the datasets model.  A dict probably makes more sense if we know we will be handling multiple files.  Currently we have a single fetch url coupled with that list.

We could update the url to be the bucket directory and then list the file names and have the HMI compose the paths on the fly.

**Comment by brandomr** [comment]
@toddroper I do think a dict would be preferable if we can make it work. What would the flow look like from the HMI Server standpoint in that case? They'd create the dataset with something like:

```
   "file_names":{
      "data1.csv":"",
      "data2.csv":""
   }
```

Then we'd update it with the S3 paths once they upload the files?

**Comment by toddroper** [comment]
I think that would work for now.  We could fill it in when they retrieve the upload URL but having the HMI explicitly send the S3 path prevents us from possibly having a non-existent path in our DB.

**Review by toddroper — APPROVED** [review]

**Review by mattprintz — APPROVED** [review]

**Comment by brandomr** [comment]
One potential issue with this is that we will be showing in the `dataset` an S3 path that may _not actually_ exist if the HMI fails to upload it. Having just an array of file names puts the onus on them to ensure that the file is where it's supposed to be; retrieving the file does require an additional API call and there are no guarantees of file name uniqueness but I think that is OK.

Since I'd like to at least be able to show them some flow around dataset uploads tomorrow, @toddroper what do you think about merging this as is for now then we can tweak it later as needed?

**Pull request merged**
