### PR TITLE
Rebuilding now depends on changes to files (hashes) isntead of timestampstamps

### PR DESCRIPTION
**Pull request by mattprintz**

### CODE REVIEW

**Comment by fivegrant** [comment]
Reverted `schema/model.py` but it didn't trigger a rebuild. Is it because `model.py` now matches upstream again?

**Comment by mattprintz** [comment]
> Reverted `schema/model.py` but it didn't trigger a rebuild. Is it because `model.py` now matches upstream again?

Technically, it didn't trigger because no python files were changed in the commits on the PR now. But if it had then it wouldn't have fired as long as the md5hash in the version file matched whatever the actual versions are.

So if you rebuild before committing and there are no extra merge changes, then it won't rebuild here.

**Review by fivegrant — COMMENTED** [review]
Looks good to me but would wait to merge until #142 is in. Is it all right if I interactively rebase to remove my commits to this PR @mattprintz?

**Review by fivegrant — APPROVED** [review]
:+1: good to merge after #142

**Pull request merged**
